### ISSUE TITLE
Hardcoded paths in openface_node.py

### ISSUE THREAD

**Issue by schelian** [tue-robotics/openface_ros#2]
Thank you for this ROS wrapper, it's very helpful!

I noticed that the code assumes that OpenFace is installed in ~/openface.  At least in my case, OpenFace is somewhere else.

Perhaps the node should take the location of OpenFace as a command line argument.  (Or it could be a parameter in a launch file.)

**Comment by LoyVanBeek** [comment]
That would indeed make more sense. Would a symlink help you out for now?

**Comment by schelian** [comment]
I just edited the Python code but the symlink could also work.  Just wanted to bring it up.

Some other feature requests would be nice to have from the command line:
-saving and loading a set of representations so that learning does not always have to be done; this can be helpful in a security type application (you train offline then load the representations and test online)
-enabling/disabling the extra information the API can return (age, sex, etc.); this can be helpful when you don't want to do extra computation

**Comment by schelian** [comment]
Hi all, I just wanted to say that saving and loading a set of representations is straightforward.  Here's what I added with all the imports:

import pickle

then at the after _face_dict is defined in the constructor:
        with open( 'my_face_dict.pickle', 'rb') as f:
            self._face_dict = pickle.load( f )
            print "read _face_dict" 

then and at the end of _learn_face_srv:
        with open( 'my_face_dict.pickle', 'wb' ) as f:
            pickle.dump( self._face_dict, f );
            print "wrote _face_dict"

Hope this is helpful!

**Comment by LoyVanBeek** [comment]
I'd be happy to integrate a pull request :smiley: ?
